name: Run Discord Bot

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

  # Trigger the workflow on a schedule (e.g., every Monday at 10:00 UTC)
  schedule:
    - cron: "0 10 * * MON"  # Every Monday at 10:00 UTC
    - cron: "0 10 * * WED"  # Every Wednesday at 10:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from your requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GITHUB_ACTIONS: true
        run: python bot.py
