name: Run Discord Bot

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 10:00 AM UTC+1 (9:00 AM UTC)
    - cron: '0 17 * * 3'  # Every Wednesday at 6:00 PM UTC+1 (5:00 PM UTC)
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GITHUB_ACTIONS: true
        run: python bot.py
